# Codecov Configuration
# https://docs.codecov.com/docs/codecov-yaml

codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      default:
        target: 70%
        threshold: 5%
        if_ci_failed: error
        informational: false

    patch:
      default:
        target: 80%
        threshold: 5%
        if_ci_failed: error

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

ignore:
  - "test/**/*"
  - "tests/**/*"
  - "**/test_*.py"
  - "**/*_test.py"
  - "docs/**/*"
  - "*.md"
  - "*.rst"
  - "*.txt"
  - "nix/**/*"
  - ".github/**/*"
  - "config/**/*"

flags:
  python:
    paths:
      - scripts/
    carryforward: true

  integration:
    paths:
      - test/integration/
    carryforward: false

  benchmarks:
    paths:
      - test/benchmarks/
    carryforward: false
