name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Enter development shell with `nix develop`
        2. Run command `...`
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe expected behavior...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe actual behavior...
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: What platform are you running on?
      options:
        - Linux (x86_64)
        - Linux (ARM64)
        - macOS (Intel)
        - macOS (Apple Silicon)
        - Windows (WSL2)
        - Other
    validations:
      required: true

  - type: dropdown
    id: shell
    attributes:
      label: Development Shell
      description: Which development shell are you using?
      options:
        - default (nix develop)
        - full (nix develop .#full)
        - cuda (nix develop .#cuda)
        - identity (nix develop .#identity)
        - humble (nix develop .#humble)
        - iron (nix develop .#iron)
        - rolling (nix develop .#rolling)
        - Not using Nix shell
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Information
      description: |
        Please run these commands and paste the output:
        ```bash
        nix --version
        pixi --version
        uname -a
        ```
      placeholder: |
        nix --version output
        pixi --version output
        uname -a output

  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Please copy and paste any relevant log output.
      render: shell

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues for duplicates
          required: true
        - label: I have read the documentation
          required: true
        - label: I am using the latest version from main branch
          required: false
